# Dependencies
markdown:          kramdown
highlighter:       pygments

# Permalinks
permalink:         pretty

# Server
source:            docs
destination:       _gh_pages
port:              9001
baseurl:           /
encoding:          UTF-8

repo:              https://github.com/1000hz/bootstrap-validator
cdn_bootstrap_css: //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
cdn_bootstrap_js:  //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js