# Dependencies
markdown:          rdiscount
pygments:          true

# Permalinks
permalink:         pretty

baseurl:           /

# Server
destination:       ./_gh_pages
exclude:           [".gitignore", "bower.json", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md"]
port:              9001

repo:              https://github.com/1000hz/bootstrap-validator
cdn_bootstrap_css: //netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css
cdn_bootstrap_js:  //netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js